namespace: hrms-production

replicaCount: 3

image:
  repository: 475936984863.dkr.ecr.ap-south-1.amazonaws.com/hrms/leave-service
  tag: "28de04a8"

service:
  nodePort: 30018

mysqlSecretName: "mysql-production"
