namespace: staging
replicaCount: 1
image:
  repository: 475936984863.dkr.ecr.ap-south-1.amazonaws.com/hrms/leave-service
  tag: "6fec64cd"
service:
  nodePort: 30017
mysqlSecretName: "mysql-staging"
hpa:
  enabled: true
  name: leave-service-hpa
  namespace: staging
  targetDeployment: leave-service
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

