namespace: production
replicaCount: 1
image:
  repository: 475936984863.dkr.ecr.ap-south-1.amazonaws.com/hrms/leave-service
  tag: "47952936"
service:
  nodePort: 30018
mysqlSecretName: "mysql-production"
hpa:
  enabled: true
  name: leave-service-hpa
  namespace: production
  targetDeployment: leave-service
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

