replicaCount: 1
image:
  repository: 475936984863.dkr.ecr.ap-south-1.amazonaws.com/hrms/notification-service
  tag: e4331c71
namespace: production
service:
  nodePort: 30011
secretName: mysql-production
