replicaCount: 1
image:
  repository: 475936984863.dkr.ecr.ap-south-1.amazonaws.com/hrms/notification-service
  tag: f7de3026
namespace: production
service:
  nodePort: 30011
secretName: mysql-production
hpa:
  enabled: true
  name: notification-service-hpa
  namespace: production
  targetDeployment: notification-service
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

