replicaCount: 1
image:
  repository: 475936984863.dkr.ecr.ap-south-1.amazonaws.com/hrms/notification-service
  tag: 3ce8ba22
namespace: staging
service:
  nodePort: 30010
secretName: mysql-staging
hpa:
  enabled: true
  name: notification-service-hpa
  namespace: staging
  targetDeployment: notification-service
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 60
