namespace: production

replicaCount: 1

image:
  repository: 475936984863.dkr.ecr.ap-south-1.amazonaws.com/hrms/user-service
  tag: 37bd4cca

service:
  nodePort: 30012

secretRef: mysql-production
hpa:
  enabled: true
  name: user-service-hpa
  namespace: production
  targetDeployment: user-service
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
