namespace: production

replicaCount: 3

image:
  repository: 475936984863.dkr.ecr.ap-south-1.amazonaws.com/hrms/user-service
  tag: 37bd4cca

service:
  nodePort: 30012

mysqlSecretName: mysql-production
