image:
  repository: ""
  tag: ""
  pullPolicy: Always

imagePullSecrets:
  - name: ecr-registry-secret

service:
  type: NodePort
  port: 80
  targetPort: 8000

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

env:
  APP_NAME: "User Management Service"
  APP_VERSION: "1.0.0"
  DEBUG: "False"

  # Database Configuration
  DB_NAME: "hrms_db"

  # Do not set DB_USER and DB_PASSWORD here.
  # use mysql secrets
  # DB_USER: "user"
  # DB_PASSWORD: "password"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_CHARSET: "utf8"

  # CORS was configured via the in-cluster Secret `cors-secrets` for easy management.
  # The Helm chart templates should be adjusted to read these values from the Secrets
  # CORS Configuration (comma-separated list)
  # CORS_ORIGINS: "https://localhost,http://localhost:3000,http://localhost:8080"

  # Asgardeo ORG
  ASGARDEO_ORG: "pookieland"
  ASGARDEO_CLIENT_ID: "O1swhn0zfcjJGAfxIKIfuAyoApAa"

  # Do not set ASGARDEO_CLIENT_SECRET here.
  # It is provided via the in-cluster Secret `asgardeo-secrets`.
  # ASGARDEO_CLIENT_SECRET: "DONT_PUT_IN_PLAINTEXT"

  KAFKA_BOOTSTRAP_SERVERS: "kafkathree:9092"
  REDIS_HOST: "redis"
  REDIS_PORT: 6379

# -------------------------------------------------------

  DB_USER_SECRET: "mysql-staging"
  DB_USER_KEY: "MYSQL_USER"
  DB_PASSWORD_SECRET: "mysql-staging"
  DB_PASSWORD_KEY: "MYSQL_PASSWORD"

  JWKS_URL: "https://api.asgardeo.io/t/pookieland/oauth2/jwks"
  
  EMPLOYEE_SERVICE_URL: "http://employee-service:80"
  LEAVE_SERVICE_URL: "http://leave-service:80"
  USER_SERVICE_URL: "http://user-service:80"
  AUDIT_SERVICE_URL: "http://audit-service:80"
  NOTIFICATION_SERVICE_URL: "http://notification-service:80"
  COMPLIANCE_SERVICE_URL: "http://compliance-service:80"
