namespace: staging
replicaCount: 1
image:
  repository: 475936984863.dkr.ecr.ap-south-1.amazonaws.com/hrms/user-service
  tag: 33ac73ac
service:
  nodePort: 30013
hpa:
  enabled: true
  name: user-service-hpa
  namespace: staging
  targetDeployment: user-service
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 60
secretRef: mysql-staging

env:
  KAFKA_BOOTSTRAP_SERVERS: "kafka.kafka-staging:9092"
