replicaCount: 1

image:
  repository: 475936984863.dkr.ecr.ap-south-1.amazonaws.com/hrms/audit-service
  tag: 1c2fb7f5

namespace: production

service:
  nodePort: 30015

secretRef: mysql-production

hpa:
  enabled: true
  name: audit-service-hpa
  namespace: production
  targetDeployment: audit-service
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70