replicaCount: 1
image:
  repository: 475936984863.dkr.ecr.ap-south-1.amazonaws.com/hrms/audit-service
  tag: 13a03976
namespace: staging
service:
  nodePort: 30014
secretRef: mysql-staging
hpa:
  enabled: true
  name: audit-service-hpa
  namespace: staging
  targetDeployment: audit-service
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70

env:
  KAFKA_BOOTSTRAP_SERVERS: "kafka.kafka-staging:9092"
