image:
  repository: 475936984863.dkr.ecr.ap-south-1.amazonaws.com/hrms/audit-service
  tag: 1c2fb7f5
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 8000

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

env:
  APP_NAME: "Audit Service"
  APP_VERSION: "1.0.0"
  DEBUG: "False"

  # Database Configuration
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_NAME: "hrms_db"

  # DB_USER: "user"
  # DB_PASSWORD: "password"
  DB_CHARSET: "utf8"

  # CORS Configuration (comma-separated list)
  CORS_ORIGINS: "https://localhost,http://localhost:3000,http://localhost:8080"

  # JWT/JWKS Settings
  JWKS_URL: "https://api.asgardeo.io/t/pookieland/oauth2/jwks"

  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  REDIS_HOST: "redis"
  REDIS_PORT: 6379


