apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user-service.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "user-service.fullname" . }}
      tier: backend
  template:
    metadata:
      labels:
        app: {{ include "user-service.fullname" . }}
        tier: backend
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
      - name: {{ include "user-service.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        env:
        - name: APP_NAME
          value: "{{ .Values.env.APP_NAME }}"
        - name: DB_HOST
          value: "{{ .Values.env.DB_HOST }}"
        - name: DB_PORT
          value: "{{ .Values.env.DB_PORT }}"
        - name: DB_NAME
          value: "{{ .Values.env.DB_NAME }}"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "{{ .Values.env.KAFKA_BOOTSTRAP_SERVERS }}"
        - name: REDIS_HOST
          value: "{{ .Values.env.REDIS_HOST }}"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretRef }}
              key: MYSQL_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretRef }}
              key: MYSQL_PASSWORD
        - name: AUDIT_SERVICE_URL
          value: "{{ .Values.env.AUDIT_SERVICE_URL }}"
        - name: JWKS_URL
          value: "{{ .Values.env.JWKS_URL }}"
        resources:
{{- toYaml .Values.resources | nindent 10 }}
