apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-service.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "user-service.fullname" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
      nodePort: {{ .Values.service.nodePort }}
  type: {{ .Values.service.type }}
