replicaCount: 1
image:
  repository: 475936984863.dkr.ecr.ap-south-1.amazonaws.com/hrms/compliance-service
  tag: ed9dd073
namespace: staging
service:
  nodePort: 30006
envSecret:
  name: mysql-staging
hpa:
  enabled: true
  name: compliance-service-hpa
  namespace: staging
  targetDeployment: compliance-service
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70

