apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "attendance-service.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "attendance-service.fullname" . }}
      tier: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge | default 1 }}
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable | default 0 }}
  template:
    metadata:
      labels:
        app: {{ include "attendance-service.fullname" . }}
        tier: backend
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
      - name: {{ include "attendance-service.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
        ports:
        - containerPort: 8000
        env:
          {{- range $key, $value := .Values.env }}
          {{- if ne $key "CORS_ORIGINS" }}
          - name: {{ $key }}
            value: "{{ $value }}"
          {{- end }}
          {{- end }}
          - name: CORS_ORIGINS
            valueFrom:
              secretKeyRef:
                name: cors-secrets
                key: CORS_ORIGINS
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.envSecret.name }}
                key: MYSQL_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.envSecret.name }}
                key: MYSQL_PASSWORD
        resources:
{{- toYaml .Values.resources | nindent 10 }}
