

replicaCount: 2

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

service:
  type: ClusterIP

zookeeper:
  replicaCount: 2

broker:
  persistence:
    enabled: true
    size: 10Gi
  listeners:
    - name: PLAINTEXT
      port: 9092
      type: internal
      tls: false
  log:
    retentionHours: 168
    segmentBytes: 1073741824
    cleanupPolicy: delete
