apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "leave-service.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "leave-service.name" . }}
      tier: backend
  template:
    metadata:
      labels:
        app: {{ include "leave-service.name" . }}
        tier: backend
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{- end }}
        - containerPort: 80
