apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "leave-service.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "leave-service.name" . }}
      tier: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge | default 1 }}
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable | default 0 }}
  template:
    metadata:
      labels:
        app: {{ include "leave-service.name" . }}
        tier: backend
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
      - name: leave-service
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        env:
        {{- range $key, $value := .Values.env }}
        {{- if ne $key "CORS_ORIGINS" }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{- end }}
        {{- end }}
        - name: CORS_ORIGINS
          valueFrom:
            secretKeyRef:
              name: cors-secrets
              key: CORS_ORIGINS
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysqlSecretName }}
              key: {{ .Values.mysqlUserKey }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysqlSecretName }}
              key: {{ .Values.mysqlPasswordKey }}
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
