apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "leave-service.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "leave-service.name" . }}
      tier: backend
  template:
    metadata:
      labels:
        app: {{ include "leave-service.name" . }}
        tier: backend
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
      - name: leave-service
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        env:
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{- end }}
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "{{ .Values.env.KAFKA_BOOTSTRAP_SERVERS | default \"kafka:9092\" }}"
        - name: REDIS_HOST
          value: "{{ .Values.env.REDIS_HOST | default \"redis:6379\" }}"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysqlSecretName }}
              key: {{ .Values.mysqlUserKey }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysqlSecretName }}
              key: {{ .Values.mysqlPasswordKey }}
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
