apiVersion: v1
kind: Service
metadata:
  name: {{ include "leave-service.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "leave-service.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
      nodePort: {{ .Values.service.nodePort }}
  type: {{ .Values.service.type }}
