apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: resources-and-config.yaml
    target:
      group: kafka.strimzi.io
      version: v1
      kind: Kafka
      name: kafka
  - path: nodepool-storage.yaml
    target:
      group: kafka.strimzi.io
      version: v1
      kind: KafkaNodePool
      name: dual-role
  - path: nodepool-resources.yaml
    target:
      group: kafka.strimzi.io
      version: v1
      kind: KafkaNodePool
      name: dual-role