replicaCount: 1

image:
  repository: 475936984863.dkr.ecr.ap-south-1.amazonaws.com/hrms/attendance-service
  tag: c29b7067

namespace: production

service:
  nodePort: 30019

envSecret:
  name: mysql-production
