replicaCount: 1
image:
  repository: 475936984863.dkr.ecr.ap-south-1.amazonaws.com/hrms/attendance-service
  tag: "fa14496c"
namespace: staging
service:
  nodePort: 30020
envSecret:
  name: mysql-staging
hpa:
  enabled: true
  name: attendance-service-hpa
  namespace: staging
  targetDeployment: attendance-service
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
