replicaCount: 1
image:
  repository: 475936984863.dkr.ecr.ap-south-1.amazonaws.com/hrms/attendance-service
  tag: bef21858
namespace: production
service:
  nodePort: 30019
envSecret:
  name: mysql-production
hpa:
  enabled: true
  name: attendance-service-hpa
  namespace: production
  targetDeployment: attendance-service
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
