apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "employee-service.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "employee-service.fullname" . }}
      tier: backend
  template:
    metadata:
      labels:
        app: {{ include "employee-service.fullname" . }}
        tier: backend
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
      - name: {{ include "employee-service.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
        ports:
        - containerPort: 80
        env:
          {{- range $key, $value := .Values.env }}
          {{- if ne $key "CORS_ORIGINS" }}
          - name: {{ $key }}
            value: "{{ $value }}"
          {{- end }}
          {{- end }}
          - name: CORS_ORIGINS
            valueFrom:
              secretKeyRef:
                name: cors-secrets
                key: CORS_ORIGINS
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretRef }}
                key: MYSQL_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretRef }}
                key: MYSQL_PASSWORD
        {{- with .Values.livenessProbe }}
        livenessProbe:
          {{- if or (not .type) (eq .type "http") }}
          httpGet:
            path: {{ .path }}
            port: {{ .port }}
          {{- else if eq .type "tcp" }}
          tcpSocket:
            port: {{ .port }}
          {{- end }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          {{- if .timeoutSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
          {{- end }}
          {{- if .failureThreshold }}
          failureThreshold: {{ .failureThreshold }}
          {{- end }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- if or (not .type) (eq .type "http") }}
          httpGet:
            path: {{ .path }}
            port: {{ .port }}
          {{- else if eq .type "tcp" }}
          tcpSocket:
            port: {{ .port }}
          {{- end }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          {{- if .timeoutSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
          {{- end }}
          {{- if .failureThreshold }}
          failureThreshold: {{ .failureThreshold }}
          {{- end }}
        {{- end }}
        {{- with .Values.startupProbe }}
        startupProbe:
          httpGet:
            path: {{ .path }}
            port: {{ .port }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          {{- if .failureThreshold }}
          failureThreshold: {{ .failureThreshold }}
          {{- end }}
        {{- end }}
        resources:
{{- toYaml .Values.resources | nindent 10 }}
