replicaCount: 1
image:
  repository: 475936984863.dkr.ecr.ap-south-1.amazonaws.com/hrms/employee-service
  tag: a11cd4e2
namespace: production
service:
  nodePort: 30009
secretRef: mysql-production
hpa:
  enabled: true
  name: employee-service-hpa
  namespace: production
  targetDeployment: employee-service
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
livenessProbe: null
readinessProbe: null
startupProbe: null
