replicaCount: 1
image:
  repository: 475936984863.dkr.ecr.ap-south-1.amazonaws.com/hrms/employee-service
  tag: e2aaaf00
namespace: staging
service:
  nodePort: 30016
secretRef: mysql-staging
hpa:
  enabled: true
  name: employee-service-hpa
  namespace: staging
  targetDeployment: employee-service
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
livenessProbe: null
readinessProbe: null
startupProbe: null
