replicaCount: 1
image:
  repository: 475936984863.dkr.ecr.ap-south-1.amazonaws.com/hrms/employee-service
  tag: 8486ec4e
namespace: staging
service:
  nodePort: 30016
secretRef: mysql-staging
hpa:
  enabled: true
  name: employee-service-hpa
  namespace: staging
  targetDeployment: employee-service
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70

env:
  KAFKA_BOOTSTRAP_SERVERS: "kafka.kafka-staging:9092"
