apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - httproute-frontend.yaml
  - httproute-user-service.yaml
  - httproute-attendance-service.yaml
  - httproute-audit-service.yaml
  - httproute-compliance-service.yaml
  - httproute-employee-service.yaml
  - httproute-leave-service.yaml
  - httproute-notification-service.yaml
